### ISSUE TITLE
AttributeError: module 'pygloo.transport.tcp' has no attribute 'attr'

### ISSUE THREAD

**Issue by fminiati** [ray-project/pygloo#18]
Hi

I am running Big Sur on an iMac mid 2015 (Quad-Code intel i5).
I have installed pygloo using Bazel as per instructions and python3.8.

I am running your "test_allreduce" test from the shelf and get the error
below: any clue?

Many thanks!

> 
2022-11-24 19:13:11,478 INFO services.py:1263 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/***/Projects/Codes/ray/test.py", line 36, in <module>
    ray.get([test_allreduce.remote(rank, world_size, fileStore_path) for rank in range(world_size)])
  File "/Users/***/Projects/.venv/ox/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/***/Projects/.venv/ox/lib/python3.8/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::test_allreduce() (pid=61964, ip=10.179.16.163)
  File "/Users/***/Projects/Codes/ray/test.py", line 15, in test_allreduce
    attr = pygloo.transport.tcp.attr("localhost")
AttributeError: module 'pygloo.transport.tcp' has no attribute 'attr'
>

**Comment by jovany-wang** [comment]
TCP transport only works on Linux, see: https://github.com/facebookincubator/gloo/blob/cf1e1abc95d0b961222ee82b6935f76250fbcf16/gloo/CMakeLists.txt#L76C21-L76C21

**Comment by jovany-wang** [comment]
Then you should use `uv` instead of `tcp` on MacOS.

**Comment by jovany-wang** [comment]
@fminiati  Is this issue still there? or I'm going to close it in 24h.

**Comment by fminiati** [comment]
hi,
please go ahead and close it.
honestly i haven’t looked into this in a while.
will reopen it if need be.
