### ISSUE TITLE
Python 3.10 not supported?

### ISSUE THREAD

**Issue by carlosgmartin** [ray-project/pygloo#19]
I'm getting the following error:
```
$ bazel --version
bazel 6.0.0
$ python3 --version
Python 3.10.9
$ python3 setup.py install
running install
/usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pygloo.egg-info/PKG-INFO
writing dependency_links to pygloo.egg-info/dependency_links.txt
writing top-level names to pygloo.egg-info/top_level.txt
reading manifest file 'pygloo.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pygloo.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "/Users/user/Desktop/pygloo/setup.py", line 131, in <module>
    setuptools.setup(
  File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/user/Desktop/pygloo/setup.py", line 116, in run
    return pip_run(self)
  File "/Users/user/Desktop/pygloo/setup.py", line 101, in pip_run
    build()
  File "/Users/user/Desktop/pygloo/setup.py", line 78, in build
    raise RuntimeError(msg)
RuntimeError: Detected Python version 3.10, which is not supported. Only Python 3.6, 3.7, 3.8 are supported.
```

**Comment by jovany-wang** [comment]
Hi @carlosgmartin , it seems that we just haven't test on 3.10. If you need it strongly, we'll schedule to support 3.10.

**Comment by pratkpranav** [comment]
Hi @jovany-wang, when would 3.10 be available?

**Comment by jovany-wang** [comment]
@pratkpranav Sorry for the delay. I'm working on it. see https://github.com/ray-project/pygloo/pull/20

**Comment by yuxiaoba** [comment]
Hi @jovany-wang, when would 3.10 be available?

**Comment by larrylian** [comment]
@yuxiaoba  Current pyhton 3.10 is availabe. You can run `python3 setup.py install` in python 3.10 env.
